# Site settings
title: CS6XYZ Spring 2020
subtitle: Programs and Proofs
baseurl: "/cs6XYZ_s20" # the subpath of your site, e.g. /blog/
url: "http://kayceesrk.github.io" # the base hostname & protocol for your site
syllabus: "http://www.cse.iitm.ac.in/course_details.php?arg=MTk="
githubdir: "kayceesrk/cs6XYZ_s20_iitm"

# Author/user information
email: kcsrk@iitm.ac.in
twitter_username: kcsrk
github_username:  kayceesrk
authorurl: "http://kcsrk.info"
address: |
    Department of Computer Science and Engineering
    BSB 371, Indian Institute of Technology, Madras
    Chennai, India 600036

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
